name: Build and deploy blog

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        
jobs:
    build-and-deploy-blog:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
            with:
                submodules: true
                fetch-depth: 0
            
          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
                hugo-version: 'latest'
            
          - name: Build site with hugo
            run: hugo --minify

          - name: Check HTML
            uses: chabad360/htmlproofer@master
            with:
                directory: "./public"
                arguments: --only-4xx --check-favicon --check-html --assume-extension
                continue-on-error: true

          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            if: github.event_name == 'push' && github.ref == 'refs/heads/main'
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./public


        